export const seoConfig = {
  siteName: 'EdBox',
  siteUrl: process.env.NEXT_PUBLIC_APP_URL || 'https://edbox.com',
  defaultTitle: 'EdBox - AI-Powered Learning Platform | Best Alternative to Coursera, Udemy & Khan Academy',
  defaultDescription: 'EdBox is the #1 AI-powered education platform for personalized learning. Create custom courses, interactive study sets, take adaptive challenges, and master any subject with AI tutors. The best free alternative to Coursera, Udemy, Khan Academy, and Duolingo.',
  defaultKeywords: [
    'learning platform',
    'online education',
    'AI tutor',
    'personalized learning',
    'coursera alternative',
    'udemy alternative',
    'khan academy alternative',
    'online courses',
    'study platform',
    'education technology',
    'edtech',
    'AI-powered learning',
    'free courses',
    'interactive learning',
    'adaptive learning',
    'study tools',
    'flashcards',
    'quiz maker',
    'course creator',
    'learning management system',
    'e-learning platform',
  ],
  ogImage: '/og-image.png',
  twitterHandle: '@edbox',
  author: {
    name: 'EdBox Team',
    url: 'https://edbox.com/about',
  },
  organization: {
    name: 'EdBox',
    legalName: 'EdBox Inc.',
    foundingDate: '2024',
    founders: [
      {
        '@type': 'Person',
        name: 'EdBox Team',
      },
    ],
    address: {
      '@type': 'PostalAddress',
      addressCountry: 'US',
    },
    contactPoint: {
      '@type': 'ContactPoint',
      contactType: 'Customer Support',
      email: 'support@edbox.com',
    },
    sameAs: [
      'https://twitter.com/edbox',
      'https://facebook.com/edbox',
      'https://linkedin.com/company/edbox',
      'https://instagram.com/edbox',
    ],
  },
  features: [
    'AI-powered personalized learning paths',
    'Custom course creation with 10+ specialized engines',
    'Interactive study sets with adaptive flashcards',
    'Real-time AI tutoring and assistance',
    'Skill-based competency tracking',
    'Collaborative study circles',
    'Gamified learning with XP and achievements',
    'Multi-subject engines: Math, Science, Coding, Languages, Finance, Arts',
    'Offline-capable PWA',
    'Free and accessible to everyone',
  ],
  subjects: [
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Computer Science',
    'Programming',
    'Languages',
    'Finance',
    'History',
    'Writing',
    'Art & Design',
  ],
  competitors: [
    'Coursera',
    'Udemy',
    'Khan Academy',
    'Duolingo',
    'Codecademy',
    'edX',
    'Skillshare',
    'LinkedIn Learning',
    'Brilliant',
    'Quizlet',
  ],
};

export const structuredDataBase = {
  '@context': 'https://schema.org',
  '@type': 'EducationalOrganization',
  name: seoConfig.siteName,
  url: seoConfig.siteUrl,
  logo: `${seoConfig.siteUrl}/logo_new.jpg`,
  description: seoConfig.defaultDescription,
  sameAs: seoConfig.organization.sameAs,
  foundingDate: seoConfig.organization.foundingDate,
  address: seoConfig.organization.address,
  contactPoint: seoConfig.organization.contactPoint,
};
