-- Function to get a list of creators (users with XP > 10000)
CREATE OR REPLACE FUNCTION get_creators(limit_count INT)
RETURNS TABLE (
    user_id UUID,
    username TEXT,
    avatar_url TEXT,
    bio TEXT,
    follower_count BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        p.id as user_id,
        p.username,
        p.avatar_url,
        p.bio,
        (SELECT COUNT(*) FROM followers WHERE followed_id = p.id) as follower_count
    FROM
        user_profiles p
    WHERE
        p.xp > 10000 -- Let's define creators as users with > 10000 XP for now
    ORDER BY
        follower_count DESC
    LIMIT
        limit_count;
END;
$$ LANGUAGE plpgsql;

-- We also need a way to follow/unfollow creators. Let's create a table for that.
CREATE TABLE IF NOT EXISTS followers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    followed_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(follower_id, followed_id)
);

ALTER TABLE followers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can see who they follow"
ON followers FOR SELECT
USING (auth.uid() = follower_id);

CREATE POLICY "Users can follow other users"
ON followers FOR INSERT
WITH CHECK (auth.uid() = follower_id);

CREATE POLICY "Users can unfollow other users"
ON followers FOR DELETE
USING (auth.uid() = follower_id);
