-- Create the study_sets table to hold sets of terms and definitions
CREATE TABLE IF NOT EXISTS study_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    is_public BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    original_study_set_id BIGINT REFERENCES study_sets(id) ON DELETE SET NULL
);

-- Add RLS to the study_sets table
ALTER TABLE study_sets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own study sets and public sets" 
ON study_sets FOR SELECT 
USING (auth.uid() = user_id OR is_public = true);

CREATE POLICY "Users can create study sets"
ON study_sets FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own study sets"
ON study_sets FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own study sets"
ON study_sets FOR DELETE
USING (auth.uid() = user_id);


-- Create the study_set_items table for the terms and definitions within a set
CREATE TABLE IF NOT EXISTS study_set_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_set_id BIGINT REFERENCES study_sets(id) ON DELETE CASCADE NOT NULL,
    term TEXT NOT NULL,
    definition TEXT NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add RLS to the study_set_items table
ALTER TABLE study_set_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage items in sets they own"
ON study_set_items FOR ALL
USING (auth.uid() = (SELECT user_id FROM study_sets WHERE id = study_set_id));

CREATE POLICY "Users can view items in public sets"
ON study_set_items FOR SELECT
USING ((SELECT is_public FROM study_sets WHERE id = study_set_id) = true);


-- Function to remix a study set
CREATE OR REPLACE FUNCTION remix_study_set(p_study_set_id BIGINT, p_user_id UUID)
RETURNS BIGINT AS $$
DECLARE
    new_study_set_id BIGINT;
    original_set study_sets%ROWTYPE;
BEGIN
    -- 1. Get the original study set details
    SELECT * INTO original_set FROM study_sets WHERE id = p_study_set_id;

    -- Ensure the original set is public
    IF original_set.is_public = false THEN
        RAISE EXCEPTION 'Only public study sets can be remixed.';
    END IF;

    -- 2. Create a new study set for the user
    INSERT INTO study_sets (user_id, title, description, is_public, original_study_set_id)
    VALUES (p_user_id, 'Remix of ' || original_set.title, original_set.description, false, p_study_set_id)
    RETURNING id INTO new_study_set_id;

    -- 3. Copy the study set items from the original to the new set
    INSERT INTO study_set_items (study_set_id, term, definition, sort_order)
    SELECT new_study_set_id, term, definition, sort_order
    FROM study_set_items
    WHERE study_set_id = p_study_set_id;

    -- 4. Return the new study set ID
    RETURN new_study_set_id;

END;
$$ LANGUAGE plpgsql;
