-- Create the profiles table to store user information.
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    country TEXT,
    education TEXT,
    age INTEGER,
    interests TEXT[],
    onboarding_completed BOOLEAN DEFAULT false
);

-- Create a new table to store content saved by the user from the feed.
CREATE TABLE IF NOT EXISTS saved_feed_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    feed_item_id TEXT NOT NULL, -- The ID of the item from the feed
    feed_item_type TEXT NOT NULL, -- e.g., 'quiz', 'video', 'article'
    saved_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    content JSONB, -- Store the full content of the feed item
    CONSTRAINT unique_user_feed_item UNIQUE (user_id, feed_item_id)
);

-- Add RLS policies for the new table.
ALTER TABLE saved_feed_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own saved items."
ON saved_feed_items FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own saved items."
ON saved_feed_items FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own saved items."
ON saved_feed_items FOR DELETE
USING (auth.uid() = user_id);
