-- Create a join table to link study sets with study circles
CREATE TABLE IF NOT EXISTS circle_study_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    circle_id BIGINT REFERENCES study_circles(id) ON DELETE CASCADE NOT NULL,
    study_set_id BIGINT REFERENCES study_sets(id) ON DELETE CASCADE NOT NULL,
    shared_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(circle_id, study_set_id) -- A set can only be shared once in a circle
);

-- Add RLS
ALTER TABLE circle_study_sets ENABLE ROW LEVEL SECURITY;

-- Function to check if a user is a member of a circle
CREATE OR REPLACE FUNCTION is_circle_member(p_circle_id BIGINT, p_user_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM circle_members
        WHERE circle_id = p_circle_id AND user_id = p_user_id
    );
END;
$$ LANGUAGE plpgsql;


-- Policies for circle_study_sets
CREATE POLICY "Circle members can view shared study sets"
ON circle_study_sets FOR SELECT
USING (is_circle_member(circle_id, auth.uid()));

CREATE POLICY "Circle members can share study sets to the circle"
ON circle_study_sets FOR INSERT
WITH CHECK (is_circle_member(circle_id, auth.uid()) AND auth.uid() = shared_by_user_id);

CREATE POLICY "Users who shared a set can remove it"
ON circle_study_sets FOR DELETE
USING (auth.uid() = shared_by_user_id);

-- Function to get study sets for a circle
CREATE OR REPLACE FUNCTION get_study_sets_for_circle(p_circle_id BIGINT)
RETURNS TABLE (
    id BIGINT,
    title TEXT,
    description TEXT,
    user_id UUID,
    username TEXT,
    avatar_url TEXT,
    shared_at TIMESTAMP WITH TIME ZONE
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        ss.id,
        ss.title,
        ss.description,
        ss.user_id,
        up.username,
        up.avatar_url,
        css.created_at as shared_at
    FROM
        circle_study_sets css
    JOIN
        study_sets ss ON css.study_set_id = ss.id
    LEFT JOIN
        user_profiles up ON ss.user_id = up.id
    WHERE
        css.circle_id = p_circle_id
    ORDER BY
        css.created_at DESC;
END;
$$ LANGUAGE plpgsql;
